# Generated by Django 5.1.5 on 2025-01-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mail', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('address', models.CharField(default='', max_length=300)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('House', 'House'), ('Hostels', 'Hostels'), ('Hotel', 'Hotel'), ('Restaurant', 'Restaurant')], default='House', max_length=20)),
                ('description', models.TextField(max_length=1000)),
                ('is_student_only', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, default='', upload_to='house_images/')),
            ],
        ),
    ]
