# Generated by Django 5.1.5 on 2025-01-30 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='is_student_only',
        ),
        migrations.AddField(
            model_name='house',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_houses', to=settings.AUTH_USER_MODEL),
        ),
    ]
