# Generated by Django 5.1.5 on 2025-02-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_remove_house_is_student_only_house_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='houses/'),
        ),
    ]
