# Generated by Django 5.1.5 on 2025-02-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_house_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image2',
            field=models.ImageField(blank=True, default='', upload_to='houses/'),
        ),
        migrations.AddField(
            model_name='house',
            name='image3',
            field=models.ImageField(blank=True, default='', upload_to='houses/'),
        ),
    ]
