# Generated by Django 5.1.5 on 2025-02-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_appliedhouses'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
    ]
